# Generated by Django 5.1.2 on 2025-06-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('chat_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Bot Keys',
                'verbose_name_plural': 'Bot Keys',
            },
        ),
    ]
