# Generated by Django 5.1.2 on 2025-06-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contact_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': 'Base', 'verbose_name_plural': 'Base'},
        ),
        migrations.AlterField(
            model_name='contactour',
            name='latitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactour',
            name='longitude',
            field=models.TextField(blank=True, null=True),
        ),
    ]
