# Generated by Django 5.1.2 on 2025-06-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_base_options_alter_contactour_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='is_main',
            field=models.BooleanField(default=True),
        ),
    ]
