# Generated by Django 5.1.2 on 2025-06-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productimages_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='is_main',
        ),
    ]
